class basic_url:
    home = "https://gasb.org/"
    about_us = 'https://gasb.org/about-us'
    about_the_gasb = 'https://gasb.org/about-us/about-the-gasb'
    standards_setting_process = 'https://gasb.org/about-us/about-the-gasb/standards-setting-process'
    post_implementation_review_process = 'https://gasb.org/about-us/about-the-gasb/post-implementation-review-process'
    board_members = 'https://gasb.org/about-us/board-members'
    senior_staff = 'https://gasb.org/about-us/senior-staff'
    governmental_accounting_standards_advisory_council = 'https://gasb.org/about-us/governmental-accounting-standards-advisory-council'
    gasb_and_the_user_community = 'https://gasb.org/about-us/gasb-and-the-user-community'
    academics = 'https://gasb.org/academics'
    financial_statement_users = 'https://gasb.org/about-us/gasb-and-the-user-community/financial-statement-users'
    contact_us = 'https://gasb.org/about-us/contact-us'
    standards_and_guidance = 'https://gasb.org/standards-and-guidance'
    Login = 'https://gars.gasb.org/Login'
    pronouncements = 'https://gasb.org/standards-and-guidance/pronouncements'
    technical_inquiry_service = 'https://gasb.org/standards-and-guidance/technical-inquiry-service'
    projects = 'https://gasb.org/projects'
    gars = "https://gars.gasb.org/Login"
    current_projects = 'https://gasb.org/projects/current-projects'
    recently_completed_projects = 'https://gasb.org/projects/recently-completed-projects'
    other_research_and_staff_projects = 'https://gasb.org/projects/other-research-and-staff-projects'
    documents_for_public_comment = 'https://gasb.org/projects/documents-for-public-comment'
    comment_letters = 'https://gasb.org/archive/comment-letters'
    news_and_meetings = 'https://gasb.org/news-and-meetings'
    live_meetings = 'https://gasb.org/news-and-meetings/live-meetings'
    upcoming_meetings = 'https://gasb.org/news-and-meetings/upcoming-meetings'
    past_meetings = 'https://gasb.org/news-and-meetings/past-meetings'
    in_the_news = 'https://gasb.org/news-and-meetings/in-the-news'
    other_articles = 'https://gasb.org/news-and-meetings/other-articles'
    educational_webinars = 'https://gasb.org/news-and-meetings/educational-webinars'
    podcasts = 'https://gasb.org/news-and-meetings/podcasts'
    request_a_gasb_speaker = 'https://gasb.org/news-and-meetings/request-a-gasb-speaker'
    media_contacts = 'https://gasb.org/news-and-meetings/media-contacts'
    signup = 'https://gasb.org/signup'
    archive = 'https://gasb.org/archive'
    terms_of_use = 'https://accountingfoundation.org/page/detail?pageId=/terms-of-use.html'
    faf_careers_and_advisory_roles = 'https://accountingfoundation.org/faf-careers-and-advisory-roles'
    twitterlink = 'https://twitter.com/FAFNorwalk'
    youtubelink = 'https://www.youtube.com/channel/UCwG1i9nAWif7P2H1ySQ5mYw'
    linkdnlink = 'https://www.linkedin.com/company/governmental-accounting-standards-board-gasb-'
    privacypolicy = 'https://accountingfoundation.org/privacypolicy'
    copyright_permission = 'https://gasb.org/copyright-permission'

class contructed_url:
    def construct_expected_url(word):
        return f"https://gasb.org/search?query={word}"